apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apkatest
      tier: backend
      tract: stable
  template:
    metadata:
      labels:
        app: apkatest
        tier: backend
        tract: stable
    spec:
      containers:
      - name: backend
        image: "isur96/example-backend"
        ports:
          - name: http
            containerPort: 3000
        env:
        - name: DBUSER
          value: db
        - name: DBHOST
          value: 10.233.105.34
        - name: DBNAME
          value: db
        - name: DBPASSWORD
          value: db
        - name: DBPORT
          value: "5432"
