apiVersion: v1
kind: Service
metadata:
  name: frontend1
spec:
  selector:
    app: apkatest
    tier: frontend1
  ports:
    - protocol: TCP
      port: 31800
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apkatest
      tier: frontend1
      track: stable
  template:
    metadata:
      labels:
        app: apkatest
        tier: frontend1
        track: stable
    spec:
      containers:
      - name: frontendapp1
        image: "isur96/example-frontend-1"
        env:
        - name: BACKEND_SERVER
          value: "10.233.105.42"
        - name: BACKEND_PORT
          value: "3000"
      nodeSelector:
        kubernetes.io/hostname: worker5
