kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-apkatest
  labels:
    type: local
    app: postgres-apkatest
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-apkatest"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-apkatest
  labels:
    app: postgres-apkatest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi